const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Behaviors.EightDir,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.SetLayerScroll
	];
};
self.C3_JsPropNameTable = [
	{Coluna: 0},
	{linha: 0},
	{eh_boss: 0},
	{visitada: 0},
	{Sala: 0},
	{MapaSalas: 0},
	{vida: 0},
	{moedas: 0},
	{arma_atual: 0},
	{pode_atacar: 0},
	{direcao_encarada: 0},
	{pode_dar_dash: 0},
	{dano_ataque: 0},
	{invulneravel: 0},
	{"8Direções": 0},
	{Cronômetro: 0},
	{Player: 0},
	{Teclado: 0},
	{AreaAtaque: 0},
	{Moeda: 0},
	{velocidade: 0},
	{dano: 0},
	{sala_pertence: 0},
	{ativo: 0},
	{Inimigo: 0},
	{Sólido: 0},
	{Parede: 0},
	{dono: 0},
	{salaVizinha: 0},
	{Porta: 0},
	{Lestrigao: 0},
	{InimigoFamily: 0},
	{SalasAlvo: 0},
	{SalasGeradas: 0},
	{ColunaAtual: 0},
	{LinhaAtual: 0},
	{NovaColuna: 0},
	{NovaLinha: 0},
	{Direcao: 0},
	{Tentativas: 0},
	{BossColuna: 0},
	{BossLinha: 0},
	{MaiorDistancia: 0},
	{SalaAtual: 0}
];

self.InstanceType = {
	Sala: class extends self.ISpriteInstance {},
	MapaSalas: class extends self.IArrayInstance {},
	Player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	AreaAtaque: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Parede: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Lestrigao: class extends self.ISpriteInstance {},
	InimigoFamily: class extends self.ISpriteInstance {}
}